Add documentation for caching issue
avo-hq/docs.avohq.io pull request #186
Opened 2024-04-02 09:27 UTC by gabrielgiroe1

Problem: cached rows on table do not update when record's associations suffer changes

2024-04-05 09:47 UTC, Paul-Bob commented on docs/3.0/cache.md
> +
```suggestion
:::warning
```

2024-04-05 09:47 UTC, Paul-Bob commented on docs/3.0/cache.md
> +
```suggestion
## Problem: cached rows on table do not update when record's associations suffer changes
:::warning

Solution 1: touch: true on association
Solution 2: override cache_hash method on resource to take associations in consideration
:::

```

2024-04-11 19:23 UTC, adrianthedev requested changes
Left some suggestions about how to change them to give our users more context and help.

2024-04-11 19:23 UTC, adrianthedev commented on docs/3.0/cache.md
> +## Problem: cached rows on table do not update when record's associations suffer changes
Let's not say "problem" in the title.

```suggestion
## Cached rows on the table do not update when the record's associations update
```

2024-04-11 19:23 UTC, adrianthedev commented on docs/3.0/cache.md
> +:::
We need to show examples of how that's achieved and not in a warning.

The structure is like so:

### Solution 1

use touch true..... <please fill in the rest>

```ruby
# example parent model with association

# example child model with association and touch true
```

### Solution 2

Avo, internally, uses the `cache_hash` method to compute the hash that will be remembered by the caching driver when displaying the rows.

You can take control and override it on that particular resource to take the association into account.

```ruby{5-13}
class Avo::Resources::User < Avo::BaseResource
  def fields
    # your fields
  end

  def cache_hash
    # record.post will now be taken under consideration 
    result = [record, file_hash, record.post]

    if parent_record.present?
      result << parent_record
    end

    result
  end
end
```

2024-04-21 19:30 UTC, gabrielgiroe1 commented
We close this because it is related to #200

2024-04-21 19:30 UTC, closed without merging