Add info on has_many association extra option
avo-hq/docs.avohq.io pull request #255
Opened 2024-07-24 10:51 UTC by binarygit

Docs for https://github.com/avo-hq/avo/pull/3048

2024-08-01 15:19 UTC, adrianthedev requested changes
This needs renaming too.

Let's show the full field declaration and shoa a screenshot with the result.

2024-08-01 17:30 UTC, binarygit commented
Done @adrianthedev

2024-08-01 21:53 UTC, adrianthedev requested changes
Thanks for the rename.

Let's also show the full field declaration and show a screenshot with the result.

The user will get much more context of of that.

2024-08-06 06:32 UTC, Paul-Bob commented on docs/3.0/associations/has_many.md
> +
```suggestion
<VersionReq version="3.11" />
```

2024-08-06 07:29 UTC, binarygit commented
@Paul-Bob I updated the gif and also the PR description :pray:

2024-08-06 07:32 UTC, Paul-Bob approved these changes

2024-08-06 07:32 UTC, merged